### ISSUE TITLE
[BUG] ZoomEye Errors

### ISSUE THREAD

**Issue by ssnkhan** [ninoseki/mihari#242] opened 2021-04-29 23:52 UTC
### **Describe the bug**
ZoomEye usage returns an error, suggesting that API settings are incorrect.

### **Steps to reproduce**
1. Write a ZoomEye query, e.g., `"x08\x08\x08\x08" +after:"2021-01-01"`
2. Convert to Mihari rule `mihari zoomeye ...`

### **Expected behavior**
Should return results from the ZoomEye API.

### **Actual behavior**
```
*A* `NoMethodError` *occured in background*: undefined method `zoomeye_api_key=' for #<Mihari::Config:0x0000562b9643a658>
Did you mean?  zoomeye_username=
```/var/lib/gems/2.7.0/gems/mihari-2.3.0/lib/mihari/config.rb:54:in `block (2 levels) in load_from_yaml'
/var/lib/gems/2.7.0/gems/mihari-2.3.0/lib/mihari/config.rb:53:in `each'
/var/lib/gems/2.7.0/gems/mihari-2.3.0/lib/mihari/config.rb:53:in `block in load_from_yaml'
/var/lib/gems/2.7.0/gems/mihari-2.3.0/lib/mihari/config.rb:81:in `configure'
/var/lib/gems/2.7.0/gems/mihari-2.3.0/lib/mihari/config.rb:52:in `load_from_yaml'
/var/lib/gems/2.7.0/gems/mihari-2.3.0/lib/mihari/cli.rb:91:in `load_configuration'
/var/lib/gems/2.7.0/gems/mihari-2.3.0/lib/mihari/cli.rb:96:in `run_analyzer'
/var/lib/gems/2.7.0/gems/mihari-2.3.0/lib/mihari/commands/zoomeye.rb:15:in `block in zoomeye'
/var/lib/gems/2.7.0/gems/mihari-2.3.0/lib/mihari/cli.rb:76:in `with_error_handling'
/var/lib/gems/2.7.0/gems/mihari-2.3.0/lib/mihari/commands/zoomeye.rb:14:in `zoomeye'```
```

### **Screenshots**
N/A

### **System Information:**
- OS: Ubuntu 20.04 LTS
- Ruby version: 2.7
- Mihari version: 2.3.0

### **Additional context**
I checked https://github.com/ninoseki/mihari/issues/240. I did a `sudo gem install mihari`, and also tried setting the `ZOOMEYE_API_KEY` via `export` and by configuring via `--config`. Tested in a local and production environment, with the error being returned in both.

**Comment by ninoseki** [comment] 2021-04-30 00:18
The issue is fixed in #241. 
The fix will be included in the next release.

**Comment by ninoseki** [comment] 2021-04-30 00:19
Oops, I misread your claim. Let me check.

**Comment by ninoseki** [comment] 2021-04-30 00:22
Okay,
> The fix will be included in the next release.
Is correct. 

I develop the tool in `master` branch which includes unreleased changes. Docs may also refer to things which are not included in the latest published version.

**Closed by ninoseki** 2021-04-30 00:22 UTC
Labels: bug
